version: "3"

# IPv4 only
# docker network create http_network

# IPv4/IPv6 network
# docker network create http_network --ipv6 --subnet "fd00:0000:0000:0000::/64"
# Refer to https://github.com/hardware/mailserver/#ipv6-support for more information.

networks:
  http_network:
    external: true
  mail_network:
    external: false

services:
  traefik:
    image: "traefik:2.2"
    container_name: "traefik"
    restart: ${RESTART_MODE}
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory" # for test only
      - "--certificatesresolvers.myresolver.acme.email=root@msync.work"
      - "--certificatesresolvers.myresolver.acme.storage=/etc/traefik/acme/acme.json"
    ports:
      - "443:443"
      - "80:80"
      #- "8080:8080"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      #- ${VOLUMES_ROOT_PATH}/traefik/traefik.toml:/traefik.toml:ro
      - ${VOLUMES_ROOT_PATH}/traefik/acme:/etc/traefik/acme

    labels:
      # Defaults for all containers
      - traefik.enable=true
      # Redirect to https
      - traefik.http.routers.http-catchall.rule=Host(`mx.${MAILSERVER_DOMAIN}`)
      - traefik.http.routers.http-catchall.entrypoints=http
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.http-catchall.middlewares=redirect-to-https
      # Traefik dashboard
      - traefik.http.routers.traefik.rule=Host(`mx.${MAILSERVER_DOMAIN}`)
      - traefik.http.routers.traefik.entrypoints=https
      - traefik.http.routers.traefik.tls.certresolver=myresolver
      - traefik.http.routers.traefik.middlewares=auth
      - traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$oixaNJzq$$CwE5rRUM2wu87.on0u0sx/
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - traefik.docker.network=http_network
    networks:
      - http_network

  mailserver:
    image: mxserver/mailserver:${MAILSERVER_DOCKER_TAG}
    container_name: "mailserver"
    restart: ${RESTART_MODE}
    domainname: ${MAILSERVER_DOMAIN}                    # Mail server A/MX/FQDN & reverse PTR = mail.domain.tld.
    hostname: ${MAILSERVER_HOSTNAME}
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.mailserver-redirect.redirectscheme.scheme=https
      - traefik.http.routers.mailserverns.middlewares=mailserver-redirect
      - traefik.http.routers.mailserverns.rule=Host(`spam.${MAILSERVER_DOMAIN}`)
      - traefik.http.routers.mailserverns.entrypoints=http
      - traefik.http.routers.mailserver.rule=Host(`spam.${MAILSERVER_DOMAIN}`)
      - traefik.http.routers.mailserver.entrypoints=https
      - traefik.http.routers.mailserver.tls=true
      - traefik.http.routers.mailserver.tls.certresolver=myresolver
      - traefik.http.services.mailserver.loadbalancer.server.port=11334
      - traefik.docker.network=http_network
    # extra_hosts:                          - Required for external database (on other server or for local databases on host without docker)
    #  - "mariadb:xx.xx.xx.xx"              - Replace with IP address of MariaDB server
    #  - "redis:xx.xx.xx.xx"                - Replace with IP address of Redis server
    ports:
      - "25:25"       # SMTP                - Required
    # - "110:110"     # POP3       STARTTLS - Optional - For webmails/desktop clients
      - "143:143"     # IMAP       STARTTLS - Optional - For webmails/desktop clients
    #  - "465:465"     # SMTPS      SSL/TLS  - Optional - Enabled for compatibility reason, otherwise disabled
      - "587:587"     # Submission STARTTLS - Optional - For webmails/desktop clients
      - "993:993"     # IMAPS      SSL/TLS  - Optional - For webmails/desktop clients
    #  - "995:995"     # POP3S      SSL/TLS  - Optional - For webmails/desktop clients
      - "4190:4190"   # SIEVE      STARTTLS - Optional - Recommended for mail filtering
    environment:
      - DBPASS=${DATABASE_USER_PASSWORD}       # MariaDB database password (required)
      - RSPAMD_PASSWORD=${RSPAMD_PASSWORD}     # Rspamd WebUI password (required)
    # - ADD_DOMAINS=aa.tld, www.bb.tld...      # Add additional domains separated by commas (needed for dkim keys etc.)
    # - DEBUG_MODE=true                        # Enable Postfix, Dovecot, Rspamd and Unbound verbose logging
    # - ENABLE_POP3=true                       # Enable POP3 protocol
    # - ENABLE_FETCHMAIL=true                  # Enable fetchmail forwarding
    # - DISABLE_RATELIMITING=false             # Enable ratelimiting policy
    # - DISABLE_CLAMAV=true                    # Disable virus scanning
    # - DISABLE_SIGNING=true                   # Disable DKIM/ARC signing
    # - DISABLE_GREYLISTING=true               # Disable greylisting policy
    #
    # Full list : https://github.com/hardware/mailserver#environment-variables
    #
    volumes:
      - ${VOLUMES_ROOT_PATH}/mail:/var/mail
      - ${VOLUMES_ROOT_PATH}/traefik/acme:/etc/letsencrypt/acme
    depends_on:
      - mariadb
      - redis
    networks:
      - mail_network
      - http_network

  # Administration interface
  # https://github.com/hardware/postfixadmin
  # http://postfixadmin.sourceforge.net/
  # Configuration : https://github.com/hardware/mailserver/wiki/Postfixadmin-initial-configuration
  postfixadmin:
    image: mxserver/postfixadmin
    container_name: "postfixadmin"
    restart: ${RESTART_MODE}
    domainname: ${MAILSERVER_DOMAIN}
    hostname: ${MAILSERVER_HOSTNAME}
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.postfixadmin-redirect.redirectscheme.scheme=https
      - traefik.http.routers.postfixadminns.middlewares=postfixadmin-redirect
      - traefik.http.routers.postfixadminns.rule=Host(`postfixadmin.${MAILSERVER_DOMAIN}`)
      - traefik.http.routers.postfixadminns.entrypoints=http
      - traefik.http.routers.postfixadmin.rule=Host(`postfixadmin.${MAILSERVER_DOMAIN}`)
      - traefik.http.routers.postfixadmin.entrypoints=https
      - traefik.http.routers.postfixadmin.tls=true
      - traefik.http.routers.postfixadmin.tls.certresolver=myresolver
      - traefik.http.services.postfixadmin.loadbalancer.server.port=8888
      - traefik.docker.network=http_network
    environment:
      - DBPASS=${DATABASE_USER_PASSWORD}
    depends_on:
      - mailserver
      - mariadb
    networks:
      - mail_network
      - http_network

  # Webmail (Optional)
  # https://github.com/hardware/rainloop
  # https://www.rainloop.net/
  # Configuration : https://github.com/hardware/mailserver/wiki/Rainloop-initial-configuration
  rainloop:
    image: mxserver/rainloop
    container_name: "rainloop"
    restart: ${RESTART_MODE}
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.rainloop-redirect.redirectscheme.scheme=https
      - traefik.http.routers.rainloopns.middlewares=rainloop-redirect
      - traefik.http.routers.rainloopns.rule=Host(`webmail.${MAILSERVER_DOMAIN}`)
      - traefik.http.routers.rainloopns.entrypoints=http
      - traefik.http.routers.rainloop.rule=Host(`webmail.${MAILSERVER_DOMAIN}`)
      - traefik.http.routers.rainloop.entrypoints=https
      - traefik.http.routers.rainloop.tls=true
      - traefik.http.routers.rainloop.tls.certresolver=myresolver
      - traefik.http.services.rainloop.loadbalancer.server.port=8888
      - traefik.docker.network=http_network
    volumes:
      - ${VOLUMES_ROOT_PATH}/rainloop:/rainloop/data
    networks:
      - mail_network
      - http_network

  # Authoritative DNS server (Optional)
  # https://github.com/hardware/nsd-dnssec
  # https://www.nlnetlabs.nl/projects/nsd/
  # Configuration : https://github.com/hardware/mailserver/wiki/NSD-initial-configuration
  #nsd:
  #  image: mxserver/nsd-dnssec
  #  container_name: "nsd"
  #  restart: ${RESTART_MODE}
  #  ports:
  #    - "53:53"
  #    - "53:53/udp"
  #  volumes:
  #    - ${VOLUMES_ROOT_PATH}/nsd/conf:/etc/nsd
  #    - ${VOLUMES_ROOT_PATH}/nsd/zones:/zones
  #    - ${VOLUMES_ROOT_PATH}/nsd/db:/var/db/nsd

  # Database
  # https://github.com/docker-library/mariadb
  # https://mariadb.org/
  mariadb:
    image: mariadb/server:10.3
    container_name: "mariadb"
    restart: ${RESTART_MODE}
    # Info : These variables are ignored when the volume already exists (if databases was created before).
    #  #- MYSQL_ROOT_PASSWORD=Ki4ndZa
    environment:
      - MARIADB_DATABASE=postfix
      - MARIADB_USER=postfix
      - MARIADB_PASSWORD=${DATABASE_USER_PASSWORD}
      - MARIADB_RANDOM_ROOT_PASSWORD=yes 
    volumes:
      - ${VOLUMES_ROOT_PATH}/mysql/db:/var/lib/mysql
    networks:
      - mail_network

  # Database
  # https://github.com/docker-library/redis
  # https://redis.io/
  redis:
    image: redis:6.0-alpine
    container_name: "redis"
    restart: ${RESTART_MODE}
    command: redis-server --appendonly yes
    volumes:
      - ${VOLUMES_ROOT_PATH}/redis/db:/data
    networks:
      - mail_network

# IPv6NAT
# https://github.com/robbertkl/docker-ipv6nat
# https://hub.docker.com/r/robbertkl/ipv6nat/
  ipv6nat:
    image: robbertkl/ipv6nat
    container_name: ipv6nat
    restart: ${RESTART_MODE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /lib/modules:/lib/modules:ro
    depends_on:
      - traefik
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    network_mode: "host"
